/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as InvestidoresRouteImport } from './routes/investidores'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PublicoRouteImport } from './routes/publico'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ApiInvitesRouteImport } from './routes/api/invites'
import { Route as ApiPricingInquiriesRouteImport } from './routes/api/pricing-inquiries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidoresRoute = InvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoRoute = PublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesRoute = ApiInvitesRouteImport.update({
  id: '/api/invites',
  path: '/api/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricingInquiriesRoute = ApiPricingInquiriesRouteImport.update({
  id: '/api/pricing-inquiries',
  path: '/api/pricing-inquiries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/investidores': typeof InvestidoresRoute
  '/profissionais': typeof ProfissionaisRoute
  '/publico': typeof PublicoRoute
  '/sobre': typeof SobreRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/pricing-inquiries': typeof ApiPricingInquiriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/investidores': typeof InvestidoresRoute
  '/profissionais': typeof ProfissionaisRoute
  '/publico': typeof PublicoRoute
  '/sobre': typeof SobreRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/pricing-inquiries': typeof ApiPricingInquiriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/investidores': typeof InvestidoresRoute
  '/profissionais': typeof ProfissionaisRoute
  '/publico': typeof PublicoRoute
  '/sobre': typeof SobreRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/pricing-inquiries': typeof ApiPricingInquiriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/investidores'
    | '/profissionais'
    | '/publico'
    | '/sobre'
    | '/api/invites'
    | '/api/pricing-inquiries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/investidores'
    | '/profissionais'
    | '/publico'
    | '/sobre'
    | '/api/invites'
    | '/api/pricing-inquiries'
  id:
    | '__root__'
    | '/'
    | '/empresas'
    | '/investidores'
    | '/profissionais'
    | '/publico'
    | '/sobre'
    | '/api/invites'
    | '/api/pricing-inquiries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRoute
  InvestidoresRoute: typeof InvestidoresRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  PublicoRoute: typeof PublicoRoute
  SobreRoute: typeof SobreRoute
  ApiInvitesRoute: typeof ApiInvitesRoute
  ApiPricingInquiriesRoute: typeof ApiPricingInquiriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidores': {
      id: '/investidores'
      path: '/investidores'
      fullPath: '/investidores'
      preLoaderRoute: typeof InvestidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico': {
      id: '/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof PublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites': {
      id: '/api/invites'
      path: '/api/invites'
      fullPath: '/api/invites'
      preLoaderRoute: typeof ApiInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pricing-inquiries': {
      id: '/api/pricing-inquiries'
      path: '/api/pricing-inquiries'
      fullPath: '/api/pricing-inquiries'
      preLoaderRoute: typeof ApiPricingInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRoute,
  InvestidoresRoute: InvestidoresRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  PublicoRoute: PublicoRoute,
  SobreRoute: SobreRoute,
  ApiInvitesRoute: ApiInvitesRoute,
  ApiPricingInquiriesRoute: ApiPricingInquiriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
